### ISSUE TITLE
Where can we find the bonds implementation using beam theory? 

### ISSUE THREAD

**Issue by dineshadepu** [anders-dc/Granular.jl#13]
Hi Anders,

I see in the readme, you specified about the implementation of cohesive strength using beam theory. 

I searched through the code base, but unable to find the implementation. Can you please point the source, if any.

**Comment by anders-dc** [comment]
Hi Dinesh, you can search for `tensile_strength` and `shear_strength` in the [interactGrains! function](https://github.com/anders-dc/Granular.jl/blob/master/src/interaction.jl#L119). The implementation is somewhat similar to [Potyondy and Strack 2004](https://doi.org/10.1016/j.ijrmms.2004.09.011). I am about to submit a paper containing the mathematical formulation.
